package ir.ac.kntu.menu.contest.admin;

public enum AdminContestMenuOption {
    ADD_QUESTION,
    REMOVE_QUESTION,
    LIST_OF_QUESTIONS,
    ADD_USER_TO_CONTEST,
    INVITE_USER_TO_CONTEST,
    REGISTER_MARK_TO_FINAL_SENT,
    EXPORT_FINAL_ANSWERS_AS_HTML_DOC,
    EXPORT_SCOREBOARD_RESULT_AS_HTML_DOC,
    SCOREBOARD,
    FINAL_RESULTS,
    EDIT_NAME,
    EDIT_START_DATETIME,
    EDIT_END_DATETIME,
    EDIT_AUTOMATIC_SCORING,
    BACK
}